import OpenAI from 'openai';
import { Rule, ModelConfig } from './types';

const SYSTEM_PROMPT_CONSOLIDATE = `You are a Principal Software Architect creating a "Golden Source of Truth" document for an AI coding agent.

Input: A raw list of rules extracted from unit tests.
Your Job:
1. DEDUPLICATE: Merge identical rules (e.g., "User must log in" + "Login must succeed" -> "Users must be authenticated").
2. ABSTRACT: Remove implementation details (e.g., mocks, specific HTTP codes if irrelevant). Focus on WHAT the system must do.
   - BAD: "Returns 400 if ID is missing."
   - GOOD: "Requests missing identifiers must be rejected as invalid."
3. CATEGORIZE: Group rules strictly by Domain/Feature (e.g., "Authentication", "Billing", "Data Validation"), NOT by filename.
4. PURGE: Aggressively discard any remaining rules that sound like testing overhead (e.g., "Mock should be called once") or basic language features.

Output strictly a JSON object with this structure. Do not output Markdown. Only valid JSON:
{
  "domains": [
    {
      "name": "Domain Name",
      "rules": ["Rule 1", "Rule 2", "Rule 3"]
    }
  ]
}`;

export async function consolidateRules(
  rawRules: Rule[],
  config: ModelConfig
): Promise<string> {
  // 1. Prepare the input payload (turn objects into a simple list string)
  const inputList = rawRules
    .map((r) => `- [${r.category}] ${r.rule} (Source: ${r.source})`)
    .join('\n');

  const openai = new OpenAI({
    apiKey: config.apiKey,
    baseURL: config.provider === 'openrouter' ? 'https://openrouter.ai/api/v1' : undefined,
  });

  console.log('Consolidating and refining rules.');

  try {
    const response = await openai.chat.completions.create({
      model: config.model, // Use a smart model here (GPT-4o or Sonnet 3.5)
      messages: [
        { role: 'system', content: SYSTEM_PROMPT_CONSOLIDATE },
        {
          role: 'user',
          content: `Here is the raw list of extracted rules. Refine them:\n\n${inputList}`,
        },
      ],
      temperature: 0.1,
      response_format: { type: 'json_object' },
    });

    const raw = response?.choices?.[0]?.message?.content ?? '{}';
    return parseAndFormatMarkdown(extractJson(raw));
  } catch (error: any) {
    const status = error?.status;
    if (status === 401) {
      throw new Error(
        `${config.provider === 'openrouter' ? 'OpenRouter' : 'OpenAI'} API error during consolidation (401 Unauthorized). Check that your API key is set correctly and has access to the requested model.`
      );
    }
    if (status === 404) {
      throw new Error(
        `${config.provider === 'openrouter' ? 'OpenRouter' : 'OpenAI'} API error during consolidation (404 Model Not Found). The model "${config.model}" is not available. Please choose a valid model ID from your provider and update DEFAULT_MODEL (or the --model flag).`
      );
    }
    if (status === 429) {
      throw new Error(
        `${config.provider === 'openrouter' ? 'OpenRouter' : 'OpenAI'} API error during consolidation (429 Rate Limit). You have hit the rate limit. Try again later or reduce concurrency.`
      );
    }
    if (status >= 500) {
      throw new Error(
        `${config.provider === 'openrouter' ? 'OpenRouter' : 'OpenAI'} API error during consolidation (server-side issue). Please try again later or switch to a different model/provider.`
      );
    }
    throw new Error(
      `Consolidation API request failed: ${error?.message || 'Unknown error. Check your network connection and API key.'}`
    );
  }
}

/** Strip <think> blocks, markdown fences, and extract JSON from LLM output. */
function extractJson(raw: string): string {
  let s = (raw ?? '').trim();
  s = s.replace(/<think>[\s\S]*?<\/think>/gi, '').trim();
  const fenceMatch = s.match(/^```(?:json)?\s*([\s\S]*?)```$/);
  if (fenceMatch) s = fenceMatch[1].trim();
  const firstBrace = s.indexOf('{');
  if (firstBrace !== -1) {
    let depth = 0;
    for (let i = firstBrace; i < s.length; i++) {
      if (s[i] === '{') depth++;
      else if (s[i] === '}') {
        depth--;
        if (depth === 0) return s.slice(firstBrace, i + 1);
      }
    }
  }
  return s;
}

function parseAndFormatMarkdown(jsonString: string): string {
  try {
    const data = JSON.parse(jsonString);
    let md = `# PROJECT CONTEXT & INVARIANTS\n`;
    md += `> Auto-generated by test-ctx. These rules are the Source of Truth.\n`;
    md += `> AI Instructions: REJECT any code changes that violate these rules.\n\n`;

    if (Array.isArray(data.domains)) {
      for (const domain of data.domains) {
        md += `## ${domain.name}\n`;
        for (const rule of domain.rules) {
          md += `- ${rule}\n`;
        }
        md += `\n`;
      }
    }
    return md;
  } catch (e) {
    console.error('Failed to parse consolidation result', e);
    throw new Error('Consolidation produced invalid JSON. Try again or use a different model.');
  }
}