import * as fs from 'fs/promises';
import * as path from 'path';

export async function writeRulesFile(
  content: string,
  outputPath: string = 'rules.md'
): Promise<void> {
  const header = `# Business Rules Extracted from Tests

> Generated by test-ctx on ${new Date().toISOString()}

---

`;

  const fullContent = header + content;

  await fs.writeFile(outputPath, fullContent, 'utf-8');
  console.log(`✓ Rules written to ${path.resolve(outputPath)}`);
}
